name: Cypress Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "develop"
      - "main"
    paths:
      - admin/src/**
      - admin/cypress/**

jobs:
  install:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: admin
    name: E2E in Edge on windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: admin
          install-command: yarn --frozen-lockfile --silent --network-timeout 1000000
          browser: edge
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3003"
          spec: cypress/e2e/**/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_APP_NAME: AI Backend
          NEXT_PUBLIC_API_URL: http://localhost:3001
          NEXT_PUBLIC_API_PATH: /api
          DOMAIN_NAME: localhost
          BASE_PATH: ""
          NEXT_PUBLIC_BASE_PATH: ""
          HEALTH_AUTH: false
          HEALTH_USERNAME: ""
          HEALTH_PASSWORD: ""
